config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    root to: "devise/registrations#new"
    get 'signup', to: 'devise/registrations#new'
    get 'login', to: 'devise/sessions#new'
  end

  get "users/:id", to: "users#show", as: 'user'

  resources :posts do
    resources :likes
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :message, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :timeline, optional: true

  include Gravtastic
  gravtastic secure: :true,
             filetype: :gif,
             size: 250,
             default: "monsterid"
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic  secure: :true,
              filetype: :gif,
              size: 250,
              default: "monsterid"


  before_save :capitalize_names

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :timeline, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  # validates :timeline_id

  private

    def capitalize_names
      self.first_name = first_name.capitalize
      self.last_name = last_name.capitalize
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    current_user ? user_path(resource) : '/signup'
  end
  private

    def require_login
      unless current_user
        redirect_to login_url
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params['post_id'])
    @post.comments.create(comment_params.merge(user_id: current_user.id))
    redirect_to post_path(params['post_id'])
  end

  private

    def comment_params
      params.require(:comment).permit(:message)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.likes.create(user_id: current_user.id)
    end
    redirect_to request.referer || posts_url
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to request.referer || posts_url
  end

  private

    def find_like
      @like = @post.likes.find(params[:id])
    end

    def already_liked?
      Like.where(user_id: current_user.id, post_id:
      params[:post_id]).exists?
    end

    def find_post
      @post = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login
  before_action :find_users, only: [:show, :index]
  before_action :find_post, only: [:show, :destroy, :update]

  def new
    if current_user
      @post = Post.new
      @timeline_id = params[:timelineid]
    else
      redirect_to login_url
    end
  end

  def create
    if params[:post][:user_id] != ""
      create_timeline_post
    else
      create_global_post
    end
    redirect_to request.referer || posts_url
    flash[:success] = "Your post has been created"
  end

  def destroy
    @post.destroy
    flash[:danger] = "Your post has been deleted"
    redirect_to request.referer || posts_url
  end

  def index
    @posts = Post.where("timeline_id IS NULL").order(created_at: :desc)
  end

  def show
  end

  def update
    if @post.update_attributes(post_params)
      flash[:success] = "Your post has been updated"
      redirect_to request.referer || posts_url
    end
  end

  private

    def post_params
      params.require(:post).permit(:message, :timeline_id)
    end

    def create_timeline_post
      @user = User.find(params[:post][:user_id])
      @post = Post.create(post_params.merge(user_id: current_user.id, timeline_id: @user.timeline.id))
    end

    def create_global_post
      @post = Post.create(post_params.merge(user_id: current_user.id))
    end

    def find_users
      @users = User.all.order(first_name: :asc)
    end

    def find_post
      @post = Post.find(params[:id])
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  after_action :add_new_timeline_to_user, only: [:create]
  private
    def sign_up_params
      params.require(:user).permit(:first_name,
                                   :last_name,
                                   :email,
                                   :password,
                                   :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:first_name,
                                    :last_name,
                                    :email,
                                    :password,
                                    :password_confirmation,
                                    :current_password)
    end

    def add_new_timeline_to_user
      @user.create_timeline(user_id: @user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login

  def show
    @user = User.find(params[:id])
    @posts = Post.where("timeline_id = #{@user.timeline.id}").order(created_at: :desc)
    @users = User.all.where("id != ?", current_user.id).order(first_name: :asc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div id="flash" class="alert alert-<%= key%>">
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Acebook</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=Shrikhand" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Noto+Serif+TC|Questrial" rel="stylesheet">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>
<header>

  <%= render 'layouts/navigation/navbar' %>
  <%= render 'layouts/flash' %>

</header>
<body>
<%= yield %>

</body>
</html>

app/views/layouts/navigation/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-top: -4em">
  <div class="container-fluid px-md-4">
    <div class="col-sm-7">
      <a class="navbar-brand" href="/posts">Acebook</a>
    </div>

    <div class="col-sm-5">
      <div class="navbar-right">
        <ul class="nav navbar-nav ">
          <% if user_signed_in? %>
            <li class="mobile-menu" id="user_name">
              <p> Hi, <%= current_user.first_name %></p>
            </li>
            <li class="mobile-menu">
              <p><%= link_to 'News Feed', posts_path %></p>
            </li>
            <li class="mobile-menu">
              <p><%= link_to 'My Profile', user_path(current_user.id) %></p>
            </li>
            <li class="mobile-menu nav-item dropdown">
              <a class="dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Users
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if current_user %>
                      <% @users.each do |user| %>
                        <a class="dropdown-item" href="/users/<%= user.id%>"><%= user.first_name %>
                          <p><%= image_tag user.gravatar_url(:size => 20) %></p>
                        </a>
                      <% end %>
                <% end %>
              </div>
            </li>
            <li class="mobile-menu">
              <p><%= link_to 'Log out', destroy_user_session_path, method: :delete %> </p>
            </li>

          <% else %>
            <p><li ><%= link_to 'Login', login_path %></li></p>
            <p><li ><%= link_to 'Signup', signup_path %></li></p>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/posts/_form.html.erb
<div class="container new-post-container">
  <% if current_user %>
    <button class="btn btn-new-post" type="button" data-toggle="collapse" data-target="#collapseExampleNew" aria-expanded="false" aria-controls="collapseExampleNew">
      New Post
    </button>
    <div class="collapse" id="collapseExampleNew">
      <div class="card card-body">
        <%= bootstrap_form_for(Post.new) do |f| %>
          <%= f.text_area :message,
                          rows: 6,
                          required: true,
                          maxlength: 1000,
                          placeholder: 'How are you feeling today?',
                          class: 'form-control' %>
          <%= f.submit "Submit", class: 'form-control create-post-button' %>
          <%= f.hidden_field :user_id, value: params[:id] %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="container new-post">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1 class="text-center">Edit your post</h1>
      <%= bootstrap_form_for(@post) do |f| %>
        <%= f.text_area :message,
                        rows: 6,
                        required: true,
                        minlength: 0,
                        maxlength: 1000,
                        placeholder: @post,
                        class: 'form-control' %>
        <%= f.submit "Submit", class: 'form-control create-post-button' %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'form' %>

<div class="container cards-container">
  <% @posts.each do |post| %>
    <div class="card">
      <div class="card-body">
        <div>
          <p class="username"><%= image_tag post.user.gravatar_url(:size => 30) %>      <%=link_to post.user.first_name, user_path(post.user.id)%></p>
          <p class="post-time"><%= post.created_at.strftime("%d/%m/%y") %></p>
        </div>
        <div class="message-container">
          <p class="post-message"><%= post.message %></p>
        </div>
        <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
        <% if pre_like %>
          <button class="btn btn-unlike">
            <i class="far fa-thumbs-down"></i>
            <%= link_to 'Unlike', post_like_path(post, pre_like), method: :delete%>
            <p class="likes-count"><%= post.likes.count %></p>
          </button>
        <% else %>
          <button class="btn btn-like">
            <i class="far fa-thumbs-up"></i>
            <%= link_to 'Like', post_likes_path(post), method: :post%>
            <p class="likes-count"><%= post.likes.count %></p>
          </button>
        <% end %>
        <% if current_user == post.user %>
          <button class="btn btn-delete">
            <i class="fas fa-trash-alt"></i>
            <%= link_to 'Delete', post, method: :delete%>
          </button>
          <button class="btn btn-edit" type="button" data-toggle="collapse" data-target="#collapseExample<%= post.id %>" aria-expanded="false" aria-controls="collapseExample">
            <i class="far fa-edit"></i>
            <label class="update">Update</label>
          </button>
        <% end %>
        <%= link_to post_path(post.id) do %>
          <p>Full Post</p>
        <% end %>
        <div class="collapse" id="collapseExample<%= post.id %>">
          <div id= "update" class="card card-body">
            <%= bootstrap_form_for(post) do |f| %>
            <p><%= f.text_area :message,
                                rows: 6,
                                required: true,
                                minlength: 0,
                                maxlength: 1000,
                                placeholder: post.message,
                                class: 'form-control' %></p>
            <%= f.submit "Accept", class: 'form-control create-post-button' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container new-post">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1 class="text-center">Create a new post</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container cards-container">
    <div class="card">
      <div class="card-body">
        <div>
          <p><%= image_tag @post.user.gravatar_url(:size => 35) %>      <%=link_to @post.user.first_name, user_path(@post.user.id)%></p>
          <p class="post-time"><%= @post.created_at.strftime("%d/%m/%y") %></p>
        </div>
        <div class="message-container">
          <p class="post-message"><%= @post.message %></p>
        </div>
        <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
        <% if pre_like %>
          <button class="btn btn-unlike">
            <i class="far fa-thumbs-down"></i>
            <%= link_to 'Unlike', post_like_path(@post, pre_like), method: :delete%>
            <p class="likes-count"><%= @post.likes.count %></p>
          </button>
        <% else %>
          <button class="btn btn-like">
            <i class="far fa-thumbs-up"></i>
            <%= link_to 'Like', post_likes_path(@post), method: :post%>
            <p class="likes-count"><%= @post.likes.count %></p>
          </button>
        <% end %>
        <% if current_user == @post.user %>
          <button class="btn btn-delete">
            <i class="fas fa-trash-alt"></i>
            <%= link_to 'Delete', @post, method: :delete%>
          </button>
          <button class="btn btn-edit" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            <i class="fa fa-sort-down"></i> Update
          </button>
          <div class="collapse" id="collapseExample">
            <div class="card card-body">
              <%= bootstrap_form_for(@post) do |f| %>
                <p><%= f.text_area :message,
                                    rows: 6,
                                    required: true,
                                    minlength: 0,
                                    maxlength: 1000,
                                    placeholder: @post.message,
                                    class: 'form-control' %></p>
                <%= f.submit "Accept", class: 'form-control create-post-button' %>
              <% end %>
            </div>
          </div>
        <% end %>
        <% if current_user %>
          <% @post.comments.each do |comment| %>
            <div class="comment" id="newCommente<%= comment.id %>">
              <div class="card card-body">
                <p><%= image_tag comment.user.gravatar_url(:size => 20) %>      <%=link_to comment.user.first_name, user_path(comment.user.id)%></p>
                <p> <%= comment.message %> </p>
              </div>
            </div>
          <% end %>
          <div class="new-comment" id="newCommentInPost<%= @post.id %>">
            <div class="card card-body">
              <%= bootstrap_form_for(Comment.new, url: post_comments_path(@post.id), method: :post) do |f| %>
              <p><%= f.text_area :message,
                                  rows: 2,
                                  required: true,
                                  minlength: 0,
                                  maxlength: 1000,
                                  placeholder: 'Your comment',
                                  class: 'form-control' %></p>
              <%= f.submit "Accept", class: 'form-control create-comment-button' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>User page</h1>

<% @users.each do |user| %>
  <p><%= user.message %></p>
<% end %>

<%= link_to new_user_path do %>
  New user
<% end %>

app/views/users/show.html.erb
<div class="container text-center">
  <%= image_tag @user.gravatar_url %><h1><%=@user.first_name%> <%=@user.last_name%></h1>
</div>

<%= render 'posts/form' %>

<div class="container cards-container">
  <% @posts.each do |post| %>
    <div class="card">
      <div class="card-body">
        <div>
          <p class="username"><%= image_tag post.user.gravatar_url(:size => 30) %>      <%=link_to post.user.first_name, user_path(post.user.id)%></p>
          <p class="post-time"><%= post.created_at.strftime("%d/%m/%y") %></p>
        </div>
        <div class="message-container">
          <p class="post-message"><%= post.message %></p>
        </div>
        <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
        <% if pre_like %>
          <button class="btn btn-unlike">
            <i class="far fa-thumbs-down"></i>
            <%= link_to 'Unlike', post_like_path(post, pre_like), method: :delete%>
            <p class="likes-count"><%= post.likes.count %></p>
          </button>
        <% else %>
          <button class="btn btn-like">
            <i class="far fa-thumbs-up"></i>
            <%= link_to 'Like', post_likes_path(post), method: :post%>
            <p class="likes-count"><%= post.likes.count %></p>
          </button>
        <% end %>
        <% if current_user == post.user %>
          <button class="btn btn-delete">
            <i class="fas fa-trash-alt"></i>
            <%= link_to 'Delete', post, method: :delete%>
          </button>
          <button class="btn btn-edit" type="button" data-toggle="collapse" data-target="#collapseExample<%= post.id %>" aria-expanded="false" aria-controls="collapseExample">
            <i class="far fa-edit"></i>
            <label class="update">Update</label>
          </button>
        <% end %>
        <%= link_to post_path(post.id) do %>
          <p>Full Post</p>
        <% end %>
        <div class="collapse" id="collapseExample<%= post.id %>">
          <div id= "update" class="card card-body">
            <%= bootstrap_form_for(post) do |f| %>
            <p><%= f.text_area :message,
                                rows: 6,
                                required: true,
                                minlength: 0,
                                maxlength: 1000,
                                placeholder: post.message,
                                class: 'form-control' %></p>
            <%= f.submit "Accept", class: 'form-control create-post-button' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>